(async()=>{
 const canvas=document.querySelector('#brain'),status=document.querySelector('#brain-status'),gl=canvas.getContext('webgl2',{antialias:true,alpha:false});
 if(!gl){status.textContent='This browser cannot open the 3D viewer. Try a browser with WebGL enabled.';return}
 try{
 const [meta,response]=await Promise.all([fetch('faq-brain.json').then(r=>r.json()),fetch('faq-brain.bin.gz')]);if(!response.ok)throw Error('Brain data is unavailable. Please reload.');const packed=await response.arrayBuffer();const checksum=[...new Uint8Array(await crypto.subtle.digest('SHA-256',packed))].map(x=>x.toString(16).padStart(2,'0')).join('');if(checksum!==meta.sha256)throw Error('Brain data verification failed. Please reload.');const raw=await new Response(new Blob([packed]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer(),view=new DataView(raw),data=new Float32Array(meta.points*6);for(let i=0;i<meta.points;i++){for(let k=0;k<3;k++)data[i*6+k]=view.getInt16(i*9+k*2,true)/16000;for(let k=0;k<3;k++)data[i*6+3+k]=view.getUint8(i*9+6+k)/255}
 const vertex=`#version 300 es
 in vec3 position;in vec3 colour;uniform vec2 angle;uniform float distance;uniform float aspect;uniform float pixelRatio;uniform float time;out vec3 tint;void main(){float cy=cos(angle.x),sy=sin(angle.x),cp=cos(angle.y),sp=sin(angle.y);vec3 p=vec3(cy*position.x-sy*position.z,position.y,sy*position.x+cy*position.z);p=vec3(p.x,cp*p.y-sp*p.z,sp*p.y+cp*p.z);float depth=max(.12,distance-p.z);gl_Position=vec4(p.x*2.1/aspect,p.y*2.1,0.,depth);gl_PointSize=clamp(2.1*pixelRatio/depth,1.,7.*pixelRatio);float wave=.55+.45*pow(.5+.5*sin(time*.8+length(position)*9.+position.x*4.),5.);tint=colour*wave;}`;
 const fragment=`#version 300 es
 precision highp float;in vec3 tint;out vec4 outColor;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;outColor=vec4(tint,(1.-smoothstep(.15,.5,d))*.9);}`;
 function shader(type,text){const s=gl.createShader(type);gl.shaderSource(s,text);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('Unable to prepare the 3D view.');return s}const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vertex));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Unable to link viewer.');gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);for(const [name,offset]of [['position',0],['colour',12]]){const loc=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,24,offset)}const u=Object.fromEntries(['angle','distance','aspect','pixelRatio','time'].map(n=>[n,gl.getUniformLocation(program,n)]));let yaw=0,pitch=.12,distance=2.4,time=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,last=performance.now();const points=new Map();
 const zoom=f=>{distance=Math.max(1.25,Math.min(5.5,distance*f))};function draw(){const dpr=Math.min(devicePixelRatio,2),w=Math.round(canvas.clientWidth*dpr),h=Math.round(canvas.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);gl.clearColor(.027,.043,.065,1);gl.clear(gl.COLOR_BUFFER_BIT);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.uniform2f(u.angle,yaw,pitch);gl.uniform1f(u.distance,distance);gl.uniform1f(u.aspect,w/h);gl.uniform1f(u.pixelRatio,dpr);gl.uniform1f(u.time,time);gl.drawArrays(gl.POINTS,0,meta.points)}
 canvas.onpointerdown=e=>{if(e.pointerType==='mouse'&&e.button!==0)return;points.set(e.pointerId,[e.clientX,e.clientY]);canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!points.has(e.pointerId))return;const old=points.get(e.pointerId),other=[...points].find(([id])=>id!==e.pointerId)?.[1];if(other){const before=Math.hypot(old[0]-other[0],old[1]-other[1]),after=Math.hypot(e.clientX-other[0],e.clientY-other[1]);if(after>0)zoom(before/after)}else{yaw+=(e.clientX-old[0])*.006;pitch=Math.max(-1.5,Math.min(1.5,pitch+(e.clientY-old[1])*.006))}points.set(e.pointerId,[e.clientX,e.clientY])};for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>points.delete(e.pointerId));canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(e.deltaY*.001))},{passive:false});canvas.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')yaw-=.1;if(e.key==='ArrowRight')yaw+=.1;if(e.key==='ArrowUp')pitch-=.1;if(e.key==='ArrowDown')pitch+=.1;if(['+','='].includes(e.key))zoom(.9);if(e.key==='-')zoom(1.1)}};
 document.querySelector('#brain-reset').onclick=()=>{yaw=0;pitch=.12;distance=2.4};document.querySelector('#brain-in').onclick=()=>zoom(.85);document.querySelector('#brain-out').onclick=()=>zoom(1.15);const pause=document.querySelector('#brain-pause');const label=()=>pause.textContent=paused?'Resume light':'Pause light';pause.onclick=()=>{paused=!paused;label()};label();
 document.querySelector('#brain-source').textContent=`${meta.neurons.toLocaleString()} / ${meta.eligible.toLocaleString()} eligible neurons · ${meta.points.toLocaleString()} sampled original points · no synthetic additions.`;const credit=document.querySelector('#source-credit');if(credit)credit.textContent=meta.notice;status.textContent='';window.brainExhibit={meta,get camera(){return [yaw,pitch,distance]},get time(){return time},draw};canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();status.textContent='Graphics connection interrupted. Reload to restore the brain.'});function frame(now){const elapsed=Math.min((now-last)/1000,.1);last=now;if(!document.hidden){if(!paused)time+=elapsed;draw()}requestAnimationFrame(frame)}requestAnimationFrame(frame);
 }catch(e){status.textContent=e.message||'Unable to load the brain. Please reload.'}
})();